// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_7hEnz7B2EGzLi5IvojRUoxpIxlo1_tY',
    appId: '1:761660855727:web:4b5b3f233d19799c178b5a',
    messagingSenderId: '761660855727',
    projectId: 'hotelbooking-d44fa',
    authDomain: 'hotelbooking-d44fa.firebaseapp.com',
    storageBucket: 'hotelbooking-d44fa.firebasestorage.app',
    measurementId: 'G-1JQ5RXD17X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKjfA0Y9UJpxI9_5JqjJnByRqwt08GIg',
    appId: '1:761660855727:android:41e6d3bd6de5efde178b5a',
    messagingSenderId: '761660855727',
    projectId: 'hotelbooking-d44fa',
    storageBucket: 'hotelbooking-d44fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArYWnFZtPLeMCERnYPSLMJM9zLycolN_4',
    appId: '1:761660855727:ios:f318fdc984f1c3f4178b5a',
    messagingSenderId: '761660855727',
    projectId: 'hotelbooking-d44fa',
    storageBucket: 'hotelbooking-d44fa.firebasestorage.app',
    iosBundleId: 'com.example.hotelbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArYWnFZtPLeMCERnYPSLMJM9zLycolN_4',
    appId: '1:761660855727:ios:f318fdc984f1c3f4178b5a',
    messagingSenderId: '761660855727',
    projectId: 'hotelbooking-d44fa',
    storageBucket: 'hotelbooking-d44fa.firebasestorage.app',
    iosBundleId: 'com.example.hotelbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_7hEnz7B2EGzLi5IvojRUoxpIxlo1_tY',
    appId: '1:761660855727:web:b319ebabe26d7094178b5a',
    messagingSenderId: '761660855727',
    projectId: 'hotelbooking-d44fa',
    authDomain: 'hotelbooking-d44fa.firebaseapp.com',
    storageBucket: 'hotelbooking-d44fa.firebasestorage.app',
    measurementId: 'G-GV6HMMCC36',
  );
}
