// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mnuHhBeT9priZc-ne1YgVOAlkSZXiW0',
    appId: '1:377534975030:web:5a16466742020f24a35c97',
    messagingSenderId: '377534975030',
    projectId: 'hotelbook-demo',
    authDomain: 'hotelbook-demo.firebaseapp.com',
    storageBucket: 'hotelbook-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYD8QlhdDQXFLy1ZKDSnGV9vrx-pHrVUY',
    appId: '1:377534975030:android:079f65ba6761b859a35c97',
    messagingSenderId: '377534975030',
    projectId: 'hotelbook-demo',
    storageBucket: 'hotelbook-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKJ5IW8JGV6jCYTpwkRfFAi7fTXwGBiMs',
    appId: '1:377534975030:ios:107f9035b332b04da35c97',
    messagingSenderId: '377534975030',
    projectId: 'hotelbook-demo',
    storageBucket: 'hotelbook-demo.firebasestorage.app',
    iosBundleId: 'com.example.hotelbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKJ5IW8JGV6jCYTpwkRfFAi7fTXwGBiMs',
    appId: '1:377534975030:ios:107f9035b332b04da35c97',
    messagingSenderId: '377534975030',
    projectId: 'hotelbook-demo',
    storageBucket: 'hotelbook-demo.firebasestorage.app',
    iosBundleId: 'com.example.hotelbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1mnuHhBeT9priZc-ne1YgVOAlkSZXiW0',
    appId: '1:377534975030:web:02b9451295c49e86a35c97',
    messagingSenderId: '377534975030',
    projectId: 'hotelbook-demo',
    authDomain: 'hotelbook-demo.firebaseapp.com',
    storageBucket: 'hotelbook-demo.firebasestorage.app',
  );

}